### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hitman-abhi** [Perceptron-DesignLab/Pipeline-Leakage-Detection#3]
out of boundary errors for water sensor reading 
for data above 1024 it does not give alert notification

**Comment by kks96500** [comment]
Problem Noted.

**Comment by singh-bhagirath** [comment]
Problem Noted.

**Comment by singh-bhagirath** [comment]
Issue resolved.
Added this
f=0
while f!=1:
sensor_data=int(input("Enter Water Sensor data : "))
if sensor_data>=0 and sensor_data<=1024:
f=1
else:
print("Invalid data")
in sensor_module.py where input of water_sensor is being taken
