### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hitman-abhi** [Perceptron-DesignLab/Pipeline-Leakage-Detection#4]
Out of boundary reading for IR sensors.
for data = 2 , it gives the output. But it should give invalid input notification.

**Comment by swapnilrajharsh** [comment]
Issue resolved.
Added boundary conditions for the same.

**Comment by swapnilrajharsh** [comment]
Issue noted.

**Comment by swapnilrajharsh** [comment]
Issue resolved.
Added this 
f=0
    while f!=1:
        sensor_data=int(input("Enter IR Sensor data : "))
        if sensor_data==0 or sensor_data==1:
            f=1
        else:
            print("Invalid data")
in sensor_module.py where input of ir_sensor is being taken
